### ISSUE TITLE
Error with cartilage parcellation

### ISSUE THREAD

**Issue by charliezhang51** [YongchengYAO/CartiMorph-Toolbox#1]
I ran into the following error when performing the cartilage parcellation step:
Output argument "versSubReg_iC_FC" (and possibly others) not assigned a value in the execution
with "CartiMorphToolbox.cal_SurfaceParcellation_FC" function.
Error in CartiMorphToolbox/CMT_morphQuant (line 11614)
Error in CartiMorphToolbox/CMT_Run_action (line 6930)
Error in CartiMorphToolbox/Button_RunValueChanged (line 14198)
Error in appdesigner.internal.service.AppManagementService/executeCallback (line 171)
Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating StateButton PrivateValueChangedFcn.

The only preprocessing step taken was converting from dicom to nifti file before inputting them into the toolbox. Cartilage surfaces segmentation and thickness mapping can be carried out successfully. 

The problem seems to be with the knee side information, as the kneeSideInfo.mat file in the \results folder is empty.

**Comment by VincentYCYao** [comment]
The knee side information file (.csv) should only contain rows for each image, such as 
```
filename1.nii.gz,right
filename2.nii.gz,left
filename3.nii.gz,right
```

- no column names
- file names with extension
- no white space
- acceptable keys: 'right', 'Right', ‘R’, 'left', 'Left', ‘L'

Debug: 
redo the whole CMT pipeline --> wait for a few seconds after loading the .csv file before pushing the `Run` button

**Comment by VincentYCYao** [comment]
@charliezhang51 any update?

**Comment by charliezhang51** [comment]
> @charliezhang51 any update?

Hi,
I have double checked the knee side information (.csv) file. It follows all the formatting requirements but still run into the same error. The kneesideinfo.mat file is empty. I have also tried reinstalling the entier toolbox and MATLAB runtime.
I am looking for other potential problems that might cause the bug (running Linux through Virtualbox, MATLAB/MATLAB runtime installation, .csv file creation/conversion).
let me know if you have any clues!
Thank you.

**Comment by VincentYCYao** [comment]
Check this log file `[CMT-folder]/Results/Task[ID]_[name]/log_*`

If the toolbox stops at the step of cartilage parcellation, you can double-check whether your input NIfTI file contains the affine matrix in the header. You can use ITK-SNAP or other tools. In ITK-SNAP, the affine matrix is the `srow_{x,y,z}`under the `Metadata`. The affine matrix should not be a zero matrix. If that is the case, try to use dcm2niix (https://github.com/rordenlab/dcm2niix) for data conversion.

**Comment by charliezhang51** [comment]
> Check this log file `[CMT-folder]/Results/Task[ID]_[name]/log_*`
> 
> If the toolbox stops at the step of cartilage parcellation, you can double-check whether your input NIfTI file contains the affine matrix in the header. You can use ITK-SNAP or other tools. In ITK-SNAP, the affine matrix is the `srow_{x,y,z}`under the `Metadata`. The affine matrix should not be a zero matrix. If that is the case, try to use dcm2niix (https://github.com/rordenlab/dcm2niix) for data conversion.

The NIfTI file does contain a non-zero affine matrix. However, I redid the data conversion using dcm2niix and the problem was resolved. Probably some information loss during data conversion.
Another change I did was to convert to .nii.gz instead of .nii format, not sure if it is related. 

Thank you!
