### ISSUE TITLE
Tibia mean thickness calculation

### ISSUE THREAD

**Issue by charliezhang51** [YongchengYAO/CartiMorph-Toolbox#2]
The mean thickness calculations for different tibial regions are = 0 or NaN. This only occurs for left knee. All other regional quantifications are normal, all right knee quantifications are normal too. Attached an example csv file for example. 
[MorphQuant.csv](https://github.com/YongchengYAO/CartiMorph-Toolbox/files/14954403/MorphQuant.csv)

**Comment by VincentYCYao** [comment]
Can you use CartiMorph Viewer to check the segmentation, parcellation, and thickness map?

Post the saved UI here.

**Comment by charliezhang51** [comment]
![1](https://github.com/YongchengYAO/CartiMorph-Toolbox/assets/96869095/8810867e-24ff-4ed8-a8bc-d9f184e80e2a)

**Comment by VincentYCYao** [comment]
You can double-check whether the surface normals are correct.

If everything appears normal, the only method to investigate the error is by sending the nii file to me. (you can send email)

**Comment by VincentYCYao** [comment]
Sorry, I thought you were using the public OAIZIB data. If that was private data, I shouldn't have asked for data sharing. BTW, I can not have access to your data. 

Possible reason for 0 mean thickness: the human knee articular cartilage is a thin soft tissue. We set a threshold (7mm) to filter out erroneous estimates.

Debugging:
1.  manually measure the thickness in tibial cartilages
2. share the NIfTI head info as follows (screenshot of ITK-SNAP)
<img width="448" alt="Screenshot 2024-04-16 at 20 03 22" src="https://github.com/YongchengYAO/CartiMorph-Toolbox/assets/49467070/5f57ffc5-d78c-4d02-b66f-b7e038ffdbce">
<img width="438" alt="Screenshot 2024-04-16 at 20 03 36" src="https://github.com/YongchengYAO/CartiMorph-Toolbox/assets/49467070/26249fe5-6f3d-4153-aff8-59f8fb2edfdd">

**Comment by charliezhang51** [comment]
Hi,
The same problem occurs with both OAI and private dataset. I have uploaded the Nifti headers below for both left and right knee. 

Left: 
![image](https://github.com/YongchengYAO/CartiMorph-Toolbox/assets/96869095/664a7137-afda-4e6d-802f-c68ab171d027)
![image](https://github.com/YongchengYAO/CartiMorph-Toolbox/assets/96869095/1b700ae9-4d2c-4fe2-902f-5e61c8747255)

Right: 
![image](https://github.com/YongchengYAO/CartiMorph-Toolbox/assets/96869095/ad3fed0e-c805-4511-8a0f-89bbf7fc2082)
![image](https://github.com/YongchengYAO/CartiMorph-Toolbox/assets/96869095/09cf863a-f8a6-4e88-bab2-fa3ccb23c083)

I can probably also calculate the tibial thickness manually using the outputs.
Thanks!

**Comment by YongchengYAO** [comment]
The nii files are fine. I am investigating the error.

**Comment by YongchengYAO** [comment]
You may try the latest release v1.0.3 which has been tested on Ubuntu 20.

I added example data and results. You can use the example data to test CMT. The example results are the outputs of the same input image.

I also updated the README file.

**Comment by charliezhang51** [comment]
The example data (right knee) could run through CMT 1.03 successfully. However, the left knee data from both OAI and private dataset runs into the same error.

**Comment by YongchengYAO** [comment]
I see. Actually, we have designed a way to handle both left and right knees correctly, which has been tested with both sides of knee MR images. 

If there are no errors that stop the toolbox and the only weird thing is the results, you can try running the pipeline with a small subset of data like 20 subjects, and check whether this is a consistent observation.

Compare the header of the sample data and your data may be helpful.

**Comment by YongchengYAO** [comment]
> ![1](https://private-user-images.githubusercontent.com/96869095/321961814-8810867e-24ff-4ed8-a8bc-d9f184e80e2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNTc4MTksIm5iZiI6MTcxNDE1NzUxOSwicGF0aCI6Ii85Njg2OTA5NS8zMjE5NjE4MTQtODgxMDg2N2UtMjRmZi00ZWQ4LWE4YmMtZDlmMTg0ZTgwZTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDE4NTE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZjlhYzAxMGI3MzhhYTU0OThhOWE2ZjdiNGFhNzgxMDlmYjhjNTFjMTM2NmQyZmEzY2YzYWQyMDJmMGRkZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BfDQSgVcYFZwHqZQkydMSFNEIfqtYgif0upjI1JG0xU)

Note that the labels for lateral and medial TC are somehow swapped. Maybe I can help to debug if you want to share this nii file via email.

**Comment by YongchengYAO** [comment]
> > ![1](https://private-user-images.githubusercontent.com/96869095/321961814-8810867e-24ff-4ed8-a8bc-d9f184e80e2a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNTc4MTksIm5iZiI6MTcxNDE1NzUxOSwicGF0aCI6Ii85Njg2OTA5NS8zMjE5NjE4MTQtODgxMDg2N2UtMjRmZi00ZWQ4LWE4YmMtZDlmMTg0ZTgwZTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI2VDE4NTE1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZjlhYzAxMGI3MzhhYTU0OThhOWE2ZjdiNGFhNzgxMDlmYjhjNTFjMTM2NmQyZmEzY2YzYWQyMDJmMGRkZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BfDQSgVcYFZwHqZQkydMSFNEIfqtYgif0upjI1JG0xU)
> 
> Note that the labels for lateral and medial TC are somehow swapped. Maybe I can help to debug if you want to share this nii file via email.

I'll debug on my side. No need for data sharing. Will update the toolbox soon, I hope.

**Comment by YongchengYAO** [comment]
The new release v1.0.4 should fix the bug -- see [release-log](https://github.com/YongchengYAO/CartiMorph-Toolbox/blob/main/Documents/CMT_releases.md).

Thank you for reporting the bug. Handling left and right knees in cartilage parcellation is a new function built upon CartiMorph. It should work as expected now.

Feel free to report bugs or errors that affect user experience. Cheers

**Comment by charliezhang51** [comment]
The bug is fixed in v1.04.
Thank you!
